pr_blog/auth/urls.py
from django.urls import path

from auth.views import RegisterView

app_name = 'custom_auth'

urlpatterns = [
    path('sign-up/', RegisterView.as_view(), name='register'),
]

pr_blog/comments/urls.py
from django.urls import path, include
from . import views


app_name = 'comments'


urlpatterns = [
    path('', views.CommentsView.as_view(), name='comm'),
]

pr_blog/main/urls.py
from django.urls import path, include
from . import views


app_name = 'main'


urlpatterns = [
    path('', views.main_home, name='main_home'),
    path('about_us', views.about_us_view, name='about_us'),
    path('contact', views.contact_view, name='contact'),
]

pr_blog/news/urls.py
from django.urls import path, include
from . import views


app_name = 'news'


urlpatterns = [
    path('', views.NewsHomeView.as_view(), name='news_home'),
    path('create', views.create, name='create'),
    path('<int:pk>', views.NewsDetailView.as_view(), name='news_detail'),
]

pr_blog/pr_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls', namespace='news')),
    path('auth/', include('auth.urls', namespace='auth')),
    path('main/', include('main.urls', namespace='main')),
    path('comments/', include('comments.urls', namespace='comments'))
]

pr_blog/comments/models.py
from django.db import models
from news.models import Articles


class Comments(models.Model):
    articles_id = models.ForeignKey(Articles, on_delete=models.CASCADE)
    author_comm = models.CharField('Автор комметария', max_length=64)
    text_comm = models.TextField('Текст комментария')
    date_comm = models.DateTimeField('Дата')

    def __str__(self):
        return self.author_comm

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

pr_blog/main/models.py
from django.db import models

pr_blog/news/models.py
from django.db import models


class Articles(models.Model):
    author = models.CharField('Автор', max_length=64)
    title = models.CharField('Название', max_length=64)
    anons = models.CharField('Анонс', max_length=250)
    full_text = models.TextField('Статья')
    date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

pr_blog/comments/forms.py
from comments.models import Comments
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea


class CommentsForm(ModelForm):
    class Meta:
        model = Comments
        fields = ['articles_id', 'author_comm', 'text_comm', 'date_comm']

        widgets = {
            "articles_id": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название статьи',
                'width': '500px'
            }),
            "author_comm": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Автор комментария',
                'width': '500px'
            }),
            "full_comm": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст комментария',
                'width': '500px'
            }),
            "date_comm": DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дата комментария',
                'width': '500px'
            })
        }

pr_blog/news/forms.py
from .models import Articles
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea


class ArticlesForm(ModelForm):
    class Meta:
        model = Articles
        fields = ['author', 'title', 'anons', 'full_text', 'date']

        widgets = {
            "author": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Автор',
                'width': '500px'
            }),
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название статьи',
                'width': '500px'
            }),
            "anons": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Анонс статьи',
                'width': '500px'
            }),
            "full_text": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст статьи',
                'width': '500px'
            }),
            "date": DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дата публикации',
                'width': '500px'
            }),
        }

pr_blog/comments/views.py
from django.shortcuts import render
from django.views.generic import ListView

from comments.forms import CommentsForm
from comments.models import Comments


class CommentsView(ListView):
    model = Comments
    template_name = 'comments/comments.html'
    context_object_name = 'comm'


def comments_create(request):
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        if form.is_valid():
            form.save()

    form = CommentsForm()
    data = {
        'form_comm': form
    }

    return render(request, data)

pr_blog/main/views.py
from django.shortcuts import render


def main_home(request):
    return render(request, 'main/main_home.html')


def about_us_view(request):
    return render(request, 'main/about_us.html')


def contact_view(request):
    return render(request, 'main/contact.html')

pr_blog/news/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from comments.forms import CommentsForm
from comments.models import Comments
from news.models import Articles
from .forms import ArticlesForm
from django.views.generic import DetailView, ListView


# def news_home(request):
#      news = Articles.objects.order_by('-date')
#      paginator = Paginator(news, 2)
#
#      page_number = request.GET.get('page')
#      page_obj = paginator.get_page(page_number)
#      return render(request, 'news/news_home.html', {'news': news, 'page_obj': page_obj})


class NewsHomeView(ListView):
     paginate_by = 2
     model = Articles
     template_name = 'news/news_home.html'
     context_object_name = 'news'


class NewsDetailView(DetailView):
    model = Articles
    template_name = 'news/detail_news.html'
    context_object_name = 'article'


class CommentsView(ListView):
    model = Comments
    template_name = 'comments/comments.html'
    context_object_name = 'comm'


def comments_create(request):
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        if form.is_valid():
            form.save()

    form = CommentsForm()
    data = {
        'form_comm': form
    }

    return render(request, data)


def create(request):
    error = ''
    if request.method == 'POST':
        form = ArticlesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('news:news_home')
        else:
            error = 'Форма была заполненна неверно!'

    form = ArticlesForm()
    data = {
        'form': form,
        'error': error
    }

    return render(request, 'news/create.html', data)

pr_blog/comments/templates/comments/comments.html
{% for com in comm %}
        <div class="alert alert-danger">
                <p>{{ com.author_comm }}</p>
                <p>{{ com.text_comm }}</p>
                <p>{{ com.date_comm }}</p>
        </div>
{% endfor%}

<form method="post" style="margin-top: 20px;">
        {% csrf_token %}
        {{ form.author_comm }}<br>
        {{ form.text_comm }}<br>
        {{ form.date_comm }}<br>
</form>

pr_blog/main/templates/main/about_us.html
{% extends 'root.html' %}
{% block content %}
    <div style="width: 100%; display: flex; flex-direction: column; align-items: center;">
        <h1 style="margin-top: 50px; color: #fff;">О нас</h1>
        <p style="color: #fff; font-size: 20px; margin-top: 20px; width: 80%;">
            IT-prosvet - это новый онлайн-ресурс, который был запущен в 2023 году. Сайт предоставляет пользователям возможность читать и добавлять статьи, посвященные IT-сфере. Наша миссия - помочь людям расширить свои знания в области информационных технологий, открывая для них новые горизонты в этой быстро развивающейся индустрии.

На IT-prosvet вы найдете широкий спектр тем, от новых технологий и программного обеспечения до кибербезопасности и искусственного интеллекта. Мы стремимся предоставлять нашим пользователям самую актуальную информацию и новости из мира IT, а также обучающие материалы и советы от профессионалов.

Кроме того, на IT-prosvet вы можете стать автором и добавить свою собственную статью, чтобы поделиться своими знаниями и опытом с другими людьми. Мы верим, что каждый может внести свой вклад в IT-сообщество и помочь другим развиваться в этой области.

Присоединяйтесь к IT-prosvet и откройте для себя новые горизонты в мире информационных технологий!
        </p>
    </div>
{% endblock %}

pr_blog/main/templates/main/contact.html
{% extends 'root.html' %}
{% block content %}
    <div style="width: 100%; display: flex; flex-direction: column; align-items: center;">
        <h1 style="margin-top: 50px; color: #fff;">Контакты</h1>
        <p style="color: #fff; font-size: 20px; margin-top: 20px; width: 80%;">
            Телефон 1: +7 (933) 453-56-32<br>
            Телефон 2: +7 (911) 833-42-12<br>
            Email: itprosvet@gmail.com<br>
        </p>
        <p style="color: #fff; font-size: 20px; margin-top: 20px; width: 80%;">
            Социальные сети:
        </p>
        <div style="display: flex; width: 15%; justify-content: space-between;">
            <a href="#" style="text-decoration: none; font-size: 20px;" class="badge badge-primary"><i class="fa-brands fa-vk"></i></a>
            <a href="#" style="text-decoration: none; font-size: 20px;" class="badge badge-primary"><i class="fa-brands fa-telegram"></i></a>
            <a href="#" style="text-decoration: none; font-size: 20px;" class="badge badge-primary"><i class="fa-brands fa-youtube"></i></a>
            <a href="#" style="text-decoration: none; font-size: 20px;" class="badge badge-primary"><i class="fa-brands fa-tiktok"></i></a>
        </div>
    </div>
{% endblock %}

pr_blog/main/templates/main/main_home.html
{% extends 'root.html' %}
{% block content %}
    <div style="width: 100%; display: flex; flex-direction: column; align-items: center;">
        <h1 style="margin-top: 50px; color: #fff;">Сайт со статьями на самые разные темы</h1>
        <h3 style="color: #fff;">Открой новые горизонты с IT и веб-дизайном - мы поможем воплотить твои идеи!</h3>
        <a href="{% url 'news:news_home' %}" type="button" class="btn btn-success" style="text-decoration: none;">Читать статьи</a>
    </div>
{% endblock %}

pr_blog/news/templates/news/create.html
{% extends 'root.html' %}
{% block content %}
    <div style="width: 100%; display: flex; flex-direction: column; align-items: center;">
        <h1 style="margin-top: 50px; color: #fff;">Форма по добавлению статьи</h1>
        <form method="post" style="margin-top: 20px;">
            {% csrf_token %}
            {{ form.title }}<br>
            {{ form.anons }}<br>
            {{ form.full_text }}<br>
            {{ form.date }}<br>
            {{ form.author }}<br>
            <button type="submit" class="btn btn-success">Добавить</button>
        </form>
    </div>
{% endblock %}

pr_blog/news/templates/news/detail_news.html
{% extends 'root.html' %}
{% block content %}
    <div class="card text-center" style="width: 100%; display: flex; flex-direction: column; align-items: center;background: #FDFCD3; width: 80%; margin-top: 50px; padding: 20px;">
        <a href="{% url 'news:news_home' %}" style="color: #000; text-decoration: none; align-self: flex-start"><i class="fa-solid fa-arrow-left"></i> Назад</a>
        <h1 class="card-text">{{ article.title }}</h1>
        <p class="card-text">{{ article.date }}</p>
        <p class="card-text" style="text-align: justify;">{{ article.full_text }}</p>
        <p class="card-text" style="align-self: flex-end;">Автор: {{ article.author }}</p>
    </div>

    <hr style="width: 80%; color: #fff; margin-top: 20px;">

    <h1 style="margin-top: 50px; color: #fff;">Комментарии</h1>

    <div>
        {% include 'comments/comments.html' %}
    </div>

{% endblock %}

pr_blog/news/templates/news/news_home.html
{% extends 'root.html' %}
{% block create %}
    <a href="{% url 'news:create' %}" type="button"><li><button class="btn btn-danger" style="color: #fff;"><i class="fa-solid fa-circle-plus"></i> Добавить запись</li></button></a>
{% endblock %}
{% block content %}
    <div style="width: 100%; display: flex; flex-direction: column; align-items: center;">
        <h1 style="margin-top: 50px; color: #fff;">Статьи на сайте </h1>

        {% for el in news %}
            <div class="card text-center" style="background: #FDFCD3; width: 50%; margin-top: 20px;">

                <div class="card-body">
                    <h4 class="card-title">{{ el.title }}</h4>
                    <p class="card-text">{{ el.anons }}</p>
                    <a href="{% url 'news:news_detail' el.id %}" class="btn btn-warning">Подробнее</a>
                </div>

                <div class="card-footer text-muted">
                    <p class="card-text">Автор: {{ el.author }}</p>
                    <p class="card-text">{{ el.date }}</p>
                </div>
            </div>
        {% endfor %}

        <nav aria-label="Page navigation example" style="margin-top: 20px;">
            <ul class="pagination">
                {% for p in paginator.page_range %}
                    {% if page_obj.number == p %}
                        <li class="page-item active"><p class="page-link">{{ p }}<span class="sr-only">(current)</span></p></li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
    </div>
{% endblock %}

pr_blog/templates/root.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="https://kit.fontawesome.com/f62ec13992.js" crossorigin="anonymous"></script>
    <style>
        body {
            background: #2c2c2c;
        }

        aside {
            float: left;
            background: #181818;
            width: 20%;
            padding: 2.5%;
            height: 100vh;
            color: #fff;
            border-right: 5px solid #4d4d4d;
        }

        aside h3 {
            margin-top: 30px;
            font-size: 28px;
        }

        aside ul {
            list-style: none;
        }

        a {
            text-decoration: none;
        }

        aside ul li {
            color: #fff;
            display: block;
            margin-top: 20px;
            transition: transform .6s ease;
        }

        aside ul li:hover, aside ul a:hover {
            color: #ed5959;
            text-decoration: none;
            transform: scale(1.05);
        }

        main {
            text-align: center;
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 80%;
        }

        .logo_text {
            font-size: 30px;
            font-weight: 900;
        }
    </style>

    {% block js %}
    {% endblock %}
</head>
<body>
    <aside>
        <div class="logo">
            <p class="logo_text">&#60;&#47;&#62;IT-prosvet</p>
        </div>
        <h3>Навигация</h3>
        <ul>
            <a href="{% url 'main:main_home' %}"><li><i class="fa-solid fa-house"></i> Главная</li></a>
            <a href="{% url 'main:about_us' %}"><li><i class="fa-solid fa-address-card"></i> Про нас</li></a>
            <a href="{% url 'news:news_home' %}"><li><i class="fa-solid fa-newspaper"></i> Новости</li></a>
            <a href="{% url 'main:contact' %}"><li><i class="fa-solid fa-paper-plane"></i> Контакты</li></a>
            <a href="{% url 'auth:register' %}"><li><i class="fa-solid fa-user"></i> Вход</li></a>

            {% block create%}
            {% endblock %}
        </ul>
    </aside>
    <main class="">
        {% block content %}
        {% endblock %}

    </main>
</body>
</html>